Module7 task1
htmlacademy-ecmascript/996317-cinemaddict-12 pull request #11
Opened 2020-09-05 22:56 UTC by geroneia

2020-09-06 03:44 UTC, Shv-sergey70 requested changes

2020-09-06 03:44 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +    // console.log(comments);
Попробуй так:
`const comments = commentsList.filter(({id}) => movieCard.comments.includes(id));`
Разберись как метод `includes` работает

2020-09-06 03:44 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +    cardPresenter.init(movieCard, commentsList);
Тут вторым параметром нужно не весь лист передавать, а отфильтрованные комментарии

2020-09-07 10:02 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +  _handleCardChange(updatedCard, commentsList) {
Метод должен принимать вторым параметром комментарии, и это правильно. Но когда ты его вызываешь, ты передаешь только первый параметр. Пример - функция `_handleFavoriteClick`, там вызывается 
```
this._changeData(
        Object.assign(
            {},
            this._card,
            {
              isFavorite: !this._card.isFavorite
            }
        )
    );
```
И второго параметра нет, а он должен быть:
```
this._changeData(
        Object.assign(
            {},
            this._card,
            {
              isFavorite: !this._card.isFavorite
            }
        ),
        this._comments
    );
```

2020-09-11 09:01 UTC, Shv-sergey70 requested changes

2020-09-12 05:06 UTC, merged

2020-09-12 21:33 UTC, geroneia commented on src/view/film-details-card.js
> +    document.addEventListener(`keydown`, this._formSubmitHandler);
Не могу понять, как сделать это((

2020-09-12 21:34 UTC, geroneia commented on src/view/film-details-card.js
> +    const index = this._commentsList.findIndex((comment) => comment.id === +value);
Это я от радости... Два дня думала, как это так - я же вижу правильный номер id в консоли, как это его нет? Пока не дошло, что там строка.

2020-09-12 21:53 UTC, geroneia commented on src/view/film-details-card.js
> +    document.addEventListener(`keydown`, this._formSubmitHandler);
Если я описываю добавление этого обработчика в презентере, то как ему указать на this._formSubmitHandler из view?