Описывает обращение к серверу и загрузку данных с сервера
htmlacademy-ecmascript/996317-cinemaddict-12 pull request #14
Opened 2020-09-19 19:32 UTC by geroneia

2020-09-21 03:08 UTC, Shv-sergey70 requested changes
Обрати внимание, что при перерисовке карточек, при их изменении, или просто если пару раз перезагрузить страницу - порядок карточек всегда разный. Надо это поправить

2020-09-21 03:08 UTC, Shv-sergey70 commented on src/utils/card.js
> +  }
Тернарный оператор?

2020-09-21 11:23 UTC, geroneia commented on src/const.js
> +export const NAMES = [
Я пока не меняла имя, потому что решила это сделать вместе с генерацией id, когда буду в следующем задании описывать добавление и удаление комментария. Этот кусок с именами остался после того, как моки удалила, положила его сюда. Сейчас снесла пока - его отсутствие ничему не мешает, как оказалось. Допишу, когда буду делать добавление коммента.

2020-09-21 11:26 UTC, geroneia commented on src/main.js
> +    };
Тут непонятно. Я не могу оставить его снаружи, потому что он использует userStatisticPresenter, который объявлен внутри then. Я вначале его объявляла снаружи (по аналогии с презентерами фильтров и фильмов), но он так не работал - рисовал нули. Поэтому все оказалось внутри then...

2020-09-21 11:28 UTC, geroneia commented on src/main.js
> +const movieListPresenter = new MovieListPresenter(siteMainElement, footerElement, cardsModel, filterModel, api, commentInput);
Я пробовала убрать filterModel и cardsModel отсюда, а в презентер импортировать FilterModel и MoviesModel, и там с ними уже что-то делать. Но они не увидят результат запроса. Не понимаю.

2020-09-21 11:29 UTC, geroneia commented on src/utils/card.js
> +  }
йес!

2020-09-23 03:58 UTC, Shv-sergey70 requested changes
1. Обрати внимание на странное поведение логики, если в одном из фильтров нет фильмов и я пытаюсь переключиться на этот фильтр. Выпадает ошибка
![Снимок экрана 2020-09-23 в 10 57 36](https://user-images.githubusercontent.com/35741647/93965165-9b89c400-fd8b-11ea-9c88-e7a2a7c561bc.png)

2. При переключении фильтров - блоки экстра списков перерисовывать не надо - они никак не зависят от фильтров или сортировки. Перерисовывается только основной список

2020-09-23 03:58 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +  _renderCard(container, movieCard, presenterStore, api) {
Сейчас при рендеринге экстра списков ты не передаешь api параметром :(

а зачем передавать api в параметре, если можно сразу через this обращаться?

2020-09-23 03:58 UTC, Shv-sergey70 commented on src/presenter/filter.js
> +    // Здесь есть проверка на текущий фильтр, но при клике следом рендерится еще раз сортировка
В этом месте поведение правильное. Если поставить здесь дебагер и посмотреть что происходит, то видно что после этого метода срабатывает `site-menu -> _menuClickHandler`. В нем то и присходит вызов колбэка который рисует еще одну статистику

2020-09-23 03:58 UTC, Shv-sergey70 commented on src/presenter/filter.js
> +    // Здесь есть проверка на текущий фильтр, но при клике следом рендерится еще раз сортировка
По поводу `_menuClickHandler`
https://gist.github.com/Shv-sergey70/96841a5a5de6a1fb8639df9707b10f61#file-site-menu-js-L4

2020-09-25 03:36 UTC, Shv-sergey70 commented
1. Заметил что в статистике мы выводим все фильмы в `all time` - там не хватает проверки на то, что фильм был просмотрен.
2. Если я в основном списке изменю фильм и сделаю его НЕ просмотренным - то стата будет по-прежнему отображать его как просмотренный

2020-09-25 03:50 UTC, Shv-sergey70 commented on src/model/movies.js
> +  setCards(updateType, cards) {
Обрати внимание на критерий:
https://up.htmlacademy.ru/ecmascript/12/criteries#d3
Метод не должен содержать в себе названия класса. То есть будет не `setCards`, а `set`. Проверь остальные методы и модели также

2020-09-25 03:50 UTC, Shv-sergey70 commented on src/utils/card.js
> +export const generateUserRank = (cards) => {
Все же было бы хорошо, если бы функция на вход принимала число фильмов и возвращала ранг. Не считая внутри ничего самостоятельно. Иначе функция получается слишком умной

2020-09-25 03:50 UTC, Shv-sergey70 commented on src/view/site-menu.js
> +    && this._menuItem === MenuItem.MOVIES))) {
Если происходит клик по количеству фильмов, то переключение фильтра не происходит

2020-09-25 03:50 UTC, Shv-sergey70 commented on src/view/site-menu.js
> +    && this._menuItem === MenuItem.MOVIES))) {
Попробуй получать всегда ссылку, с которой можно работать, вне зависимости от того, где произошел клик:
```
_menuClickHandler(evt) {
    const clickedItem = evt.target.tagName === `A` ? evt.target : evt.target.closest(`a`); // дальше уже используй только эту переменную

    if (evt.target.classList.contains(`main-navigation__item--active`)
    || evt.target.classList.contains(`main-navigation__item-count`)
    || ((evt.target.classList.contains(`main-navigation__item`)
    && this._menuItem === MenuItem.MOVIES))) {

      return;
    }

    if (evt.target.classList.contains(`main-navigation__additional`)) {
      this._menuItem = MenuItem.STATS;

    } else if (evt.target.classList.contains(`main-navigation__item`) && this._menuItem !== ``) {
      this._menuItem = MenuItem.MOVIES;
    }

    this._callback.menuClick(this._menuItem);
  }
```

2020-09-25 03:50 UTC, merged

2020-09-25 20:07 UTC, geroneia commented on src/model/movies.js
> +  setCards(updateType, cards) {
Я, видимо, не поняла этого критерия. Этот класс у меня называется Movies, поэтому в методах я оставила Cards, чтобы не запутаться в горе одинаковых методов, там, где нужно использовать и фильтры, и фильмы...