Module8 task2
htmlacademy-ecmascript/996317-cinemaddict-12 pull request #15
Opened 2020-09-25 23:40 UTC by geroneia

2020-09-26 04:54 UTC, Shv-sergey70 requested changes

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/api.js
> +      url: `${Url.COMMENTS}/${id}/${index}`,
Посмотри ТЗ, как именно выглядит адрес для удаления комментария. Ты явно передаешь 1 лишний параметр

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +        this._api.deleteComment(updateCard.id, commentIndex).then(() => {
Здесь не нужно передавать index комментария. Для удаления требуется только его ID

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/main.js
> +    render(siteHeaderElement, new ProfileRatingView(generateUserRank(getWatchedFilmsCount(cardsModel.getCards()))), RenderPosition.BEFOREEND);
Предлагаю перенести метод по определению просмотренных фильмов и их количества в модель. Так как по сути ты обрабатываешь те данные что лежат в модели - это относится к ее зоне ответственности

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +  _handleViewAction(actionType, updateType, updateCard, updateComments, updateComment, commentIndex) {
`commentIndex` тебе вряд ли здесь нужен

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +          this._commentsModel.add(updateType, updateCard, updateComments, response);
Метод вроде 4го параметра не принимает (`response`)

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +          this._commentsModel.add(updateType, updateCard, updateComments, response);
Самые актуальные данные у тебя лежат в объекте `response`. Поэтому при обновлении модели, нужно использовать данные из него. Там хранится весь обновленный список комментариев (и тогда тебе не нужно `updateComments` из параметра, так как он есть в `response`). И также там лежит объект фильма

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie.js
> +  _handleDeleteClick(deletedComment, commentIndex) {
Единственное что нужно получить из метода для удаления - это ID комментария. Сам `deletedComment` тебе вряд ли нужен

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie.js
> +          // name,
Да, это можно удалять, поля генерируются на сервере автоматически

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/view/site-menu.js
> +    || clickedItem.classList.contains(`main-navigation__item-count`)
clickedItem уже никогда не может содержать класс `main-navigation__item-count`, так как он принадлежит span.
Суть того, что мы сделали в том, чтобы всегда работать со ссылкой

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/user-statistic.js
> +    const watchedMovies = this._cards.filter((card) => card.isWatched);
__Но вот с передачей актуальных данных я все-таки не понимаю. Я думала, что я их и так передаю актуальные… В main на 42 строке я пишу, что нужно использовать cardsModel.getCards() А это не то, да?__

Дело в том, что когда ты создаешь презентер статистики ты передаешь туда актуальные данные. Но после того, как ты делаешь изменения, данные в модели меняются, но так как презентер заново не создается, он по-прежнему хранит в себе старые данные в `this._cards`. 

Поэтому в презентер статы нужно просто передавать модель фильмов и везде вместо обращений `this._cards` делать `this._cardsModel.getCards()` - тогда модель будет всегда возвращать актуальные данные. Ведь любые изменения данных происходят в модели и она владеет всеми актуальными данными

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +        this._cardPresenterCommonFilmsList[updateCard.id].setViewState(MoviePresenterViewState.DELETING);
Делая так, разве ты не сразу всем комментариям проставишь `deleting...`?

2020-09-26 04:54 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +        this._cardPresenterCommonFilmsList[updateCard.id].setViewState(MoviePresenterViewState.DELETING);
Я думаю, что можно поступить проще, и не делать эту штуку с `setViewState`. Просто когда ты нажимаешь на кнопку удалить - нужно сделать так, чтобы текст сразу менялся (то есть написать в обработчике клика этот код). 

Затем, если запрос не завершится успешно, то вызывать эффект покачивания головой, через callback. То есть делаем возможность прокинуть callback в `_handleViewAction `, и сам колбэк создаем в обработчике клика по удалению.

Из-за того, что мы создаем колбэк прямо в обработчике на удаление, он будет знать (через замыкание), как коммент надо потрясти.

Если будет не понятно - пиши, разберем подробнее

2020-09-26 10:30 UTC, geroneia commented on src/presenter/user-statistic.js
> +    const watchedMovies = this._cards.filter((card) => card.isWatched);
<тут мог бы быть мой фэйспалм> господи. дошло

2020-09-27 04:09 UTC, Shv-sergey70 requested changes

2020-09-27 04:09 UTC, Shv-sergey70 commented on src/presenter/movie-list.js
> +        this._api.addComment(updateCard, updateComment).then(() => {
По сути тебе модель комментариев в этом классе вообще не нужна

2020-09-27 04:09 UTC, Shv-sergey70 commented on src/view/film-details-card.js
> +    const deletedCommentId = evt.target.dataset.id;
По поводу колбэков, логика такая:
https://gist.github.com/Shv-sergey70/9fe496e1cf5721e612de89e0f09076d5

Тогда в случае ошибки - сработает этот колбэк, потрясется комментарий и вернется обычный текст

2020-09-27 17:51 UTC, geroneia commented on src/presenter/movie-list.js
> +        this._api.addComment(updateCard, updateComment).then(() => {
Я думала, что это пригодится, если нужно будет настроить работу без интернета (как в 9 задании).

2020-09-28 04:10 UTC, merged